### ISSUE TITLE
Optimization in PE0006.rb

### ISSUE THREAD

**Issue by MichaelVessia** [adelphimathcs/ProjectEuler-0006#1]
@MattMatero, since we are summing natural numbers from 1 to n in this problem, we can take advantage of the formula for triangular numbers.  I think you will remember it from our many math classes.  
![4950ae2d99ac2e83c67b1562e44addfd](https://cloud.githubusercontent.com/assets/5640057/8826311/9014957e-3053-11e5-8b75-214f4d3a899e.png)

**Comment by MattMatero** [comment]
Implemented. Ty
